In [1]:
import pandas as pd
from sqlalchemy import create_engine
from sqlalchemy.engine import URL

In [2]:
url = URL.create(
    "mysql+mysqlconnector",
    username="root",
    password="Hari@7Axim!",
    host="localhost",
    database="superstore_db"
)

In [3]:
engine = create_engine(url)

In [4]:
df = pd.read_csv('../data/Cleaned-Superstore.csv')

df.to_sql(
    name="superstore",     # Name of the target SQL table
    con=engine,            # SQLAlchemy engine connection
    if_exists="replace",    # How to behave if the table already exists
    index=False            # Do not write the DataFrame index as a column
)

9994

# SQL Analysis

In [5]:
# Top selling products
top_selling_products_query = """select `Product Name` as Top_selling_products from superstore 
           group by `Product Name` 
           order by sum(Quantity) desc
           limit 10"""
pd.read_sql(top_selling_products_query, con=engine)

                                Top_selling_products
0                                            Staples
1                                    Staple envelope
2                                  Easy-staple paper
3                            Staples in misc. colors
4                         KI Adjustable-Height Table
5                            Avery Non-Stick Binders
6                            Storex Dura Pro Binders
7  GBC Premium Transparent Covers with Diagonal L...
8         Situations Contoured Folding Chairs, 4/Set
9                         Staple-based wall hangings

In [6]:
# Highest Revenue Categories
highest_revenue_categories_query = """ select Category As Highest_Revenue_Categories from superstore
                                       group by Category 
                                       order by sum(Sales) desc"""
pd.read_sql(highest_revenue_categories_query, con=engine)

  Highest_Revenue_Categories
0                 Technology
1                  Furniture
2            Office Supplies

In [7]:
# Monthly Sales Report
monthly_sales_report_query = """ select `Order Month`, sum(Sales) as Monthly_sales_report from superstore
                                 group by `Order Month`  order by `Order Month`"""

pd.read_sql(monthly_sales_report_query, con=engine)

    Order Month  Monthly_sales_report
0             1            94924.8356
1             2            59751.2514
2             3           205005.4888
3             4           137762.1286
4             5           155028.8117
5             6           152718.6793
6             7           147238.0970
7             8           159044.0630
8             9           307649.9457
9            10           200322.9847
10           11           352461.0710
11           12           325293.5035

In [8]:
# Customer Analysis 
customer_analysis_with_order_counts_query = """ select `Customer Name`, sum(`Order Count`) as Total_Orders from superstore
                                                group by `Customer Name` order by sum(`Order Count`) desc 
                                                limit 10"""

pd.read_sql(customer_analysis_with_order_counts_query, con=engine)

         Customer Name  Total_Orders
0        William Brown        1369.0
1             John Lee        1156.0
2           Paul Prost        1156.0
3         Matt Abelman        1156.0
4         Edward Hooks        1024.0
5          Seth Vernon        1024.0
6  Chloris Kastensmidt        1024.0
7     Jonathan Doherty        1024.0
8           Emily Phan         961.0
9       Arthur Prichep         961.0

In [9]:
customer_analysis_total_spend_query = """ select `Customer Name`, sum(Sales) as Total_Spend from superstore
                                          group by `Customer Name` order by sum(Sales) desc 
                                          limit 10"""

pd.read_sql(customer_analysis_total_spend_query, con=engine)

        Customer Name  Total_Spend
0         Sean Miller    25043.050
1        Tamara Chand    19052.218
2        Raymond Buch    15117.339
3        Tom Ashbrook    14595.620
4       Adrian Barton    14473.571
5        Ken Lonsdale    14175.229
6        Sanjit Chand    14142.334
7        Hunter Lopez    12873.298
8        Sanjit Engle    12209.438
9  Christopher Conant    12129.072

In [10]:
# Regional Sales Comparison
regional_sales_comparison_query = """ select Region, sum(Sales) as Total_Sales from superstore
                                      group by Region order by sum(sales) desc"""
pd.read_sql(regional_sales_comparison_query, con=engine)

    Region  Total_Sales
0     West  725457.8245
1     East  678781.2400
2  Central  501239.8908
3    South  391721.9050

In [11]:
# Top Profitable Products
top_profitable_products_query = """ select `Product Name` as Top_Profitable_Products, sum(Profit) as Total_Profits from superstore
                                    group by `Product Name` order by sum(Profit) desc
                                    limit 10"""
pd.read_sql(top_profitable_products_query, con=engine)

                             Top_Profitable_Products  Total_Profits
0              Canon imageCLASS 2200 Advanced Copier     25199.9280
1  Fellowes PB500 Electric Punch Plastic Comb Bin...      7753.0390
2               Hewlett Packard LaserJet 3310 Copier      6983.8836
3                 Canon PC1060 Personal Laser Copier      4570.9347
4  HP Designjet T520 Inkjet Large Format Printer ...      4094.9766
5                  Ativa V4110MDD Micro-Cut Shredder      3772.9461
6   3D Systems Cube Printer, 2nd Generation, Magenta      3717.9714
7  Plantronics Savi W720 Multi-Device Wireless He...      3696.2820
8               Ibico EPK-21 Electric Binding System      3345.2823
9                  Zebra ZM400 Thermal Label Printer      3343.5360

In [12]:
# Customer Segmentation
customer_segment_analysis_query = """select Segment, count(*) as Total_Orders, sum(Sales) as Total_Sales, sum(Profit) as Total_Profit from superstore
                                     group by Segment order by count(*) desc, sum(Sales) desc, sum(Profit) desc
                                  """

pd.read_sql(customer_segment_analysis_query, con=engine)

       Segment  Total_Orders   Total_Sales  Total_Profit
0     Consumer          5191  1.161401e+06   134119.2092
1    Corporate          3020  7.061464e+05    91979.1340
2  Home Office          1783  4.296531e+05    60298.6785

In [13]:
# Sales Trend
sales_trend_query = """ select `Order Year` as Years, `Order Month` as Months, sum(Sales) as Total_Sales from superstore
                        group by `Order Year`, `Order Month` order by `Order Year`, `Order Month`"""

pd.read_sql(sales_trend_query, con=engine)

    Years  Months  Total_Sales
0    2014       1   14236.8950
1    2014       2    4519.8920
2    2014       3   55691.0090
3    2014       4   28295.3450
4    2014       5   23648.2870
5    2014       6   34595.1276
6    2014       7   33946.3930
7    2014       8   27909.4685
8    2014       9   81777.3508
9    2014      10   31453.3930
10   2014      11   78628.7167
11   2014      12   69545.6205
12   2015       1   18174.0756
13   2015       2   11951.4110
14   2015       3   38726.2520
15   2015       4   34195.2085
16   2015       5   30131.6865
17   2015       6   24797.2920
18   2015       7   28765.3250
19   2015       8   36898.3322
20   2015       9   64595.9180
21   2015      10   31404.9235
22   2015      11   75972.5635
23   2015      12   74919.5212
24   2016       1   18542.4910
25   2016       2   22978.8150
26   2016       3   51715.8750
27   2016       4   38750.0390
28   2016       5   56987.7280
29   2016       6   40344.5340
30   2016       7   39261.9630
31   2016       8   31115.3743
32   2016       9   73410.0249
33   2016      10   59687.7450
34   2016      11   79411.9658
35   2016      12   96999.0430
36   2017       1   43971.3740
37   2017       2   20301.1334
38   2017       3   58872.3528
39   2017       4   36521.5361
40   2017       5   44261.1102
41   2017       6   52981.7257
42   2017       7   45264.4160
43   2017       8   63120.8880
44   2017       9   87866.6520
45   2017      10   77776.9232
46   2017      11  118447.8250
47   2017      12   83829.3188